# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Patterns
email: kbd3ax@virginia.edu
description: >- # this means to ignore newlines until "baseurl:"
  HTML, CSS, and JS patterns for basic webpage layouts. Code includes:
  page of equal sections, gallery page, single item page, text page,
  and one for larger, mixed-media pages.
baseurl: "/patterns" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kbdonnally
github_username:  kbdonnally
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/css/_sass
  style: expanded # temporary! change back to compressed later
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - node_modules
  - testing
  - docs
  - python
collections:
  research:
    output: true
    permalink: /:collection/:title/
  events:
    output: true
    permalink: /:collection/:name/
  homepages:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true